package Day7;

public class printobj {
	String i ="implemented";
	
	public String toString()// this will effect the output generated by object
//	rather than giving the reference for the object when printed it will print this statement
	{
		return "successfully "+i;
	} 
	public static void main(String[] args)
	{
		printobj o =new printobj();
		System.out.println(o);//prints reference when there is no override // Hash-Code-.hashCode()//getClass()
	}

}
